@startuml
package domain <<Rectangle>> {
    class FileReference {
        + id: Long?
        + fileName: String
        + rawFilePath: String
        + filePath: URI
        + lastAccess: OffsetDateTime
    }
}

@enduml